name: "Build & Deploy Docs"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    name: "Build & Deploy CoreShop Docs"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Create Docs Directory"
        run: |
          mkdir docs

      - name: "Checkout CoreShop Docs"
        uses: "actions/checkout@v4"
        with:
          repository: "coreshop/coreshop"
          ref: "4.0"
          path: "./tmp/CoreShop"
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            docs/docs/*

      - name: "Move CoreShop Docs"
        run: |
          mkdir docs/01_CoreShop
          mv tmp/CoreShop/docs/docs/* docs/01_CoreShop

      - name: "Checkout CoreShop Batch Messenger Bundle Docs"
        uses: "actions/checkout@v4"
        with:
          repository: "coreshop/batch-messenger-bundle"
          ref: "main"
          path: "./tmp/Batch_Messenger_Bundle"
          token: ${{ secrets.DOCS_GENERATOR_ACCESS_TOKEN }}

      - name: "Move CoreShop Batch Messenger Bundle Docs"
        run: |
          mkdir docs/02_Batch_Messenger_Bundle 
          mv tmp/Batch_Messenger_Bundle/docs/* docs/02_Batch_Messenger_Bundle
          cp tmp/Batch_Messenger_Bundle/README.md docs/02_Batch_Messenger_Bundle/index.md

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          registry-url: 'https://registry.npmjs.org'

      - name: Build Docs
        run: |
          ls -la docs/01_CoreShop
          ls -la docs/02_Batch_Messenger_Bundle
          npm install
          npm run build

      - name: Archive Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            build

      - name:  Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Upload Folder
        uses: 'google-github-actions/upload-cloud-storage@v0'
        if: github.ref == 'refs/heads/4.0'
        with:
          path: 'build/'
          destination: 'cors-wolke-coreshop-docs/4.0.0'
          parent: false