name: "Build & Deploy Docs"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkout-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [
          { name: "coreshop/coreshop",                    branch: "4.0",  dir: "01_CoreShop" },
          { name: "coreshop/batch-messenger-bundle",      branch: "main", dir: "02_Batch_Messenger_Bundle" },
          { name: "coreshop/credit-bundle",               branch: "main", dir: "03_Credit_Bundle" },
          { name: "coreshop/document-route-bundle",       branch: "main", dir: "04_Document_Route_Bundle" },
          { name: "coreshop/inbound-email-rules-bundle",  branch: "main", dir: "05_Inbound_Email_Rules_Bundle" },
          { name: "coreshop/index-geo-bundle",            branch: "main", dir: "06_Index_GEO_Bundle" },
          { name: "coreshop/voucher-credit-bundle",       branch: "main", dir: "07_Voucher_Credit_Bundle" },
          { name: "coreshop/warehouse-bundle",            branch: "main", dir: "08_Warehouse_Bundle" },
          { name: "coreshop/deposit-bundle",              branch: "main", dir: "09_Deposit_Bundle" },
          { name: "coreshop/customer-cluster-bundle",     branch: "main", dir: "10_Customer_Cluster_Bundle" },
          { name: "coreshop/b2b-company-bundle",          branch: "main", dir: "11_B2B_Company_Bundle" },
          { name: "coreshop/headless-bundle",             branch: "main", dir: "12_Headless_Bundle" },
          { name: "coreshop/loyalty-bundle",              branch: "main", dir: "13_Loyalty_Bundle" }
        ]
    steps:
      - name: Checkout ${{ matrix.repo.name }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo.name }}
          ref: ${{ matrix.repo.branch }}
          path: ./tmp/${{ matrix.repo.dir }}
          token: ${{ secrets.DOCS_GENERATOR_ACCESS_TOKEN }}

      - name: Move Repository Docs
        run: |
          mkdir -p docs
          mv ./tmp/${{ matrix.repo.dir }}/docs docs/${{ matrix.repo.dir }}
          if [ -f "./tmp/${{ matrix.repo.dir }}/README.md" ]; then
            if [ ! -e "docs/${{ matrix.repo.dir }}/00_Introduction.md" ]; then
              cp ./tmp/${{ matrix.repo.dir }}/README.md docs/${{ matrix.repo.dir }}/index.md
            fi
          fi
          
          if [ -f "docs/${{ matrix.repo.dir }}/index.md" ]; then
            sed -i 's|/docs||g' docs/${{ matrix.repo.dir }}/index.md
          fi

      - name: Upload Repo Docs
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.repo.dir }}
          path: docs/${{ matrix.repo.dir }}

  build-docs:
    needs: checkout-repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: docs

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          registry-url: 'https://registry.npmjs.org'

      - name: Build Docs
        run: |
          npm install
          npm run build

      - name: Archive Final Docs
        uses: actions/upload-artifact@v3
        with:
          name: final-docs
          path: build

      - name:  Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Upload Folder
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'build/'
          destination: 'cors-wolke-coreshop-docs/4.0.0'
          parent: false